//
// Generated file, do not edit! Created by nedtool 4.6 from messages/HF_ChangeNotification.msg.
//

#ifndef _HF_CHANGENOTIFICATION_M_H_
#define _HF_CHANGENOTIFICATION_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
    #include <EtherFrame_m.h>
    #include "HyperFlowStructs.h"
    
// }}

/**
 * Class generated from <tt>messages/HF_ChangeNotification.msg:13</tt> by nedtool.
 * <pre>
 * // When packets are received by the data plane and sent to the connected controller,
 * // the OFP_PACKET_IN messages are used. If the complete packet needs to be sent to the controller, because it can not be
 * // stored in the bufer, it is encapsulated in the packet-in message.
 * packet HF_ChangeNotification
 * {
 *     DataChannelEntry entry;
 * }
 * </pre>
 */
class HF_ChangeNotification : public ::cPacket
{
  protected:
    DataChannelEntry entry_var;

  private:
    void copy(const HF_ChangeNotification& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const HF_ChangeNotification&);

  public:
    HF_ChangeNotification(const char *name=NULL, int kind=0);
    HF_ChangeNotification(const HF_ChangeNotification& other);
    virtual ~HF_ChangeNotification();
    HF_ChangeNotification& operator=(const HF_ChangeNotification& other);
    virtual HF_ChangeNotification *dup() const {return new HF_ChangeNotification(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual DataChannelEntry& getEntry();
    virtual const DataChannelEntry& getEntry() const {return const_cast<HF_ChangeNotification*>(this)->getEntry();}
    virtual void setEntry(const DataChannelEntry& entry);
};

inline void doPacking(cCommBuffer *b, HF_ChangeNotification& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, HF_ChangeNotification& obj) {obj.parsimUnpack(b);}


#endif // ifndef _HF_CHANGENOTIFICATION_M_H_

