//
// Generated file, do not edit! Created by nedtool 4.6 from messages/HF_SyncReply.msg.
//

#ifndef _HF_SYNCREPLY_M_H_
#define _HF_SYNCREPLY_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
    #include <EtherFrame_m.h>
    #include "HyperFlowStructs.h"
    typedef std::list<ControlChannelEntry> ControlChannel;
    typedef std::list<DataChannelEntry> DataChannel;
    
// }}

/**
 * Class generated from <tt>messages/HF_SyncReply.msg:16</tt> by nedtool.
 * <pre>
 * // When packets are received by the data plane and sent to the connected controller,
 * // the OFP_PACKET_IN messages are used. If the complete packet needs to be sent to the controller, because it can not be
 * // stored in the bufer, it is encapsulated in the packet-in message.
 * packet HF_SyncReply
 * {
 *     ControlChannel controlChannel;
 *     DataChannel dataChannel;
 * }
 * </pre>
 */
class HF_SyncReply : public ::cPacket
{
  protected:
    ControlChannel controlChannel_var;
    DataChannel dataChannel_var;

  private:
    void copy(const HF_SyncReply& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const HF_SyncReply&);

  public:
    HF_SyncReply(const char *name=NULL, int kind=0);
    HF_SyncReply(const HF_SyncReply& other);
    virtual ~HF_SyncReply();
    HF_SyncReply& operator=(const HF_SyncReply& other);
    virtual HF_SyncReply *dup() const {return new HF_SyncReply(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual ControlChannel& getControlChannel();
    virtual const ControlChannel& getControlChannel() const {return const_cast<HF_SyncReply*>(this)->getControlChannel();}
    virtual void setControlChannel(const ControlChannel& controlChannel);
    virtual DataChannel& getDataChannel();
    virtual const DataChannel& getDataChannel() const {return const_cast<HF_SyncReply*>(this)->getDataChannel();}
    virtual void setDataChannel(const DataChannel& dataChannel);
};

inline void doPacking(cCommBuffer *b, HF_SyncReply& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, HF_SyncReply& obj) {obj.parsimUnpack(b);}


#endif // ifndef _HF_SYNCREPLY_M_H_

