//
// Generated file, do not edit! Created by nedtool 4.6 from messages/HF_SyncRequest.msg.
//

#ifndef _HF_SYNCREQUEST_M_H_
#define _HF_SYNCREQUEST_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
    #include <EtherFrame_m.h>
    
    
// }}

/**
 * Class generated from <tt>messages/HF_SyncRequest.msg:12</tt> by nedtool.
 * <pre>
 * // When packets are received by the data plane and sent to the connected controller,
 * // the OFP_PACKET_IN messages are used. If the complete packet needs to be sent to the controller, because it can not be
 * // stored in the bufer, it is encapsulated in the packet-in message.
 * packet HF_SyncRequest
 * {
 *     int lastSyncCounter;
 * }
 * </pre>
 */
class HF_SyncRequest : public ::cPacket
{
  protected:
    int lastSyncCounter_var;

  private:
    void copy(const HF_SyncRequest& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const HF_SyncRequest&);

  public:
    HF_SyncRequest(const char *name=NULL, int kind=0);
    HF_SyncRequest(const HF_SyncRequest& other);
    virtual ~HF_SyncRequest();
    HF_SyncRequest& operator=(const HF_SyncRequest& other);
    virtual HF_SyncRequest *dup() const {return new HF_SyncRequest(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getLastSyncCounter() const;
    virtual void setLastSyncCounter(int lastSyncCounter);
};

inline void doPacking(cCommBuffer *b, HF_SyncRequest& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, HF_SyncRequest& obj) {obj.parsimUnpack(b);}


#endif // ifndef _HF_SYNCREQUEST_M_H_

