//
// Generated file, do not edit! Created by nedtool 4.6 from messages/KN_Packet.msg.
//

#ifndef _KN_PACKET_M_H_
#define _KN_PACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
    #include <EtherFrame_m.h>
    #include "KandooStructs.h"
// }}

/**
 * Class generated from <tt>messages/KN_Packet.msg:12</tt> by nedtool.
 * <pre>
 * // When packets are received by the data plane and sent to the connected controller,
 * // the OFP_PACKET_IN messages are used. If the complete packet needs to be sent to the controller, because it can not be
 * // stored in the bufer, it is encapsulated in the packet-in message.
 * packet KN_Packet
 * {
 *     KandooEntry knEntry;
 * }
 * </pre>
 */
class KN_Packet : public ::cPacket
{
  protected:
    KandooEntry knEntry_var;

  private:
    void copy(const KN_Packet& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const KN_Packet&);

  public:
    KN_Packet(const char *name=NULL, int kind=0);
    KN_Packet(const KN_Packet& other);
    virtual ~KN_Packet();
    KN_Packet& operator=(const KN_Packet& other);
    virtual KN_Packet *dup() const {return new KN_Packet(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual KandooEntry& getKnEntry();
    virtual const KandooEntry& getKnEntry() const {return const_cast<KN_Packet*>(this)->getKnEntry();}
    virtual void setKnEntry(const KandooEntry& knEntry);
};

inline void doPacking(cCommBuffer *b, KN_Packet& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, KN_Packet& obj) {obj.parsimUnpack(b);}


#endif // ifndef _KN_PACKET_M_H_

