//
// Generated file, do not edit! Created by nedtool 4.6 from messages/OFP_Features_Reply.msg.
//

#ifndef _OFP_FEATURES_REPLY_M_H_
#define _OFP_FEATURES_REPLY_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
    #include "openflow.h"
    #include "Open_Flow_Message_m.h"
    #include "MACAddress.h"
// }}

/**
 * Class generated from <tt>messages/OFP_Features_Reply.msg:14</tt> by nedtool.
 * <pre>
 * // response  to an OFP_Features_Request message
 * packet OFP_Features_Reply extends Open_Flow_Message
 * {
 *     string datapath_id;		// Datapath unique ID. The lower 48-bits are for a MAC address,
 *     					   	// while the upper 16-bits are implementer-defined.
 *     //	MACAddress address;
 *     uint32_t n_buffers;		// Max packets buffered at once.
 * 
 *     uint8_t n_tables; 		// Number of tables supported by datapath.
 * 
 *     //Features
 *     uint32_t capabilities; 	// Bitmap of support "ofp_capabilities".
 *     uint32_t reserved;
 * 
 *     //Port info
 *     uint32_t ports[]; 		//Port definitions. The number of ports is inferred from the
 *     						// length field in the header.
 * }
 * </pre>
 */
class OFP_Features_Reply : public ::Open_Flow_Message
{
  protected:
    opp_string datapath_id_var;
    uint32_t n_buffers_var;
    uint8_t n_tables_var;
    uint32_t capabilities_var;
    uint32_t reserved_var;
    uint32_t *ports_var; // array ptr
    unsigned int ports_arraysize;

  private:
    void copy(const OFP_Features_Reply& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const OFP_Features_Reply&);

  public:
    OFP_Features_Reply(const char *name=NULL, int kind=0);
    OFP_Features_Reply(const OFP_Features_Reply& other);
    virtual ~OFP_Features_Reply();
    OFP_Features_Reply& operator=(const OFP_Features_Reply& other);
    virtual OFP_Features_Reply *dup() const {return new OFP_Features_Reply(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getDatapath_id() const;
    virtual void setDatapath_id(const char * datapath_id);
    virtual uint32_t getN_buffers() const;
    virtual void setN_buffers(uint32_t n_buffers);
    virtual uint8_t getN_tables() const;
    virtual void setN_tables(uint8_t n_tables);
    virtual uint32_t getCapabilities() const;
    virtual void setCapabilities(uint32_t capabilities);
    virtual uint32_t getReserved() const;
    virtual void setReserved(uint32_t reserved);
    virtual void setPortsArraySize(unsigned int size);
    virtual unsigned int getPortsArraySize() const;
    virtual uint32_t getPorts(unsigned int k) const;
    virtual void setPorts(unsigned int k, uint32_t ports);
};

inline void doPacking(cCommBuffer *b, OFP_Features_Reply& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, OFP_Features_Reply& obj) {obj.parsimUnpack(b);}


#endif // ifndef _OFP_FEATURES_REPLY_M_H_

