//
// Generated file, do not edit! Created by nedtool 4.6 from messages/OFP_Initialize_Handshake.msg.
//

#ifndef _OFP_INITIALIZE_HANDSHAKE_M_H_
#define _OFP_INITIALIZE_HANDSHAKE_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
    #include "openflow.h"
    #include "Open_Flow_Message_m.h"
// }}

/**
 * Class generated from <tt>messages/OFP_Initialize_Handshake.msg:17</tt> by nedtool.
 * <pre>
 * //Upon session establishment, the controller sends an OFP Features Request message
 * //to get information about the capabilities of a switch. This message does
 * //not contain a body beyond the OpenFlow header. The switch responds with an
 * //OFP Features Reply message.
 * packet OFP_Initialize_Handshake extends Open_Flow_Message
 * {
 * }
 * </pre>
 */
class OFP_Initialize_Handshake : public ::Open_Flow_Message
{
  protected:

  private:
    void copy(const OFP_Initialize_Handshake& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const OFP_Initialize_Handshake&);

  public:
    OFP_Initialize_Handshake(const char *name=NULL, int kind=0);
    OFP_Initialize_Handshake(const OFP_Initialize_Handshake& other);
    virtual ~OFP_Initialize_Handshake();
    OFP_Initialize_Handshake& operator=(const OFP_Initialize_Handshake& other);
    virtual OFP_Initialize_Handshake *dup() const {return new OFP_Initialize_Handshake(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
};

inline void doPacking(cCommBuffer *b, OFP_Initialize_Handshake& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, OFP_Initialize_Handshake& obj) {obj.parsimUnpack(b);}


#endif // ifndef _OFP_INITIALIZE_HANDSHAKE_M_H_

