//
// Generated file, do not edit! Created by nedtool 4.6 from messages/OFP_Packet_Out.msg.
//

#ifndef _OFP_PACKET_OUT_M_H_
#define _OFP_PACKET_OUT_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
    #include "openflow.h"
    #include "Open_Flow_Message_m.h"
    #include <EtherFrame_m.h>
    
    inline std::ostream& operator<<(std::ostream& os, ofp_action_output action)
    {
		os << "Port (hex): " << std::hex << action.port << endl;
		return os;
	}
// }}

/**
 * Class generated from <tt>messages/OFP_Packet_Out.msg:22</tt> by nedtool.
 * <pre>
 * //When the controller decides to send a packet out through the data plane, it uses the
 * //OFP PACKET OUT message.
 * packet OFP_Packet_Out extends Open_Flow_Message
 * {
 *     uint32_t buffer_id; // ID assigned by datapath (OFP_NO_BUFFER
 *                         //if none). 
 *     uint32_t in_port; // Packet�s input port or OFPP_CONTROLLER. 
 * 
 *     ofp_action_output actions[]; // Action list. 
 *     //	 EthernetIIFrame frame;
 *     uint8_t data[0];   // Packet data. The length is inferred
 * 							//from the length field in the header.
 * 							//(Only meaningful if buffer_id == -1.) 
 * }
 * </pre>
 */
class OFP_Packet_Out : public ::Open_Flow_Message
{
  protected:
    uint32_t buffer_id_var;
    uint32_t in_port_var;
    ofp_action_output *actions_var; // array ptr
    unsigned int actions_arraysize;
    uint8_t data_var[0];

  private:
    void copy(const OFP_Packet_Out& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const OFP_Packet_Out&);

  public:
    OFP_Packet_Out(const char *name=NULL, int kind=0);
    OFP_Packet_Out(const OFP_Packet_Out& other);
    virtual ~OFP_Packet_Out();
    OFP_Packet_Out& operator=(const OFP_Packet_Out& other);
    virtual OFP_Packet_Out *dup() const {return new OFP_Packet_Out(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual uint32_t getBuffer_id() const;
    virtual void setBuffer_id(uint32_t buffer_id);
    virtual uint32_t getIn_port() const;
    virtual void setIn_port(uint32_t in_port);
    virtual void setActionsArraySize(unsigned int size);
    virtual unsigned int getActionsArraySize() const;
    virtual ofp_action_output& getActions(unsigned int k);
    virtual const ofp_action_output& getActions(unsigned int k) const {return const_cast<OFP_Packet_Out*>(this)->getActions(k);}
    virtual void setActions(unsigned int k, const ofp_action_output& actions);
    virtual unsigned int getDataArraySize() const;
    virtual uint8_t getData(unsigned int k) const;
    virtual void setData(unsigned int k, uint8_t data);
};

inline void doPacking(cCommBuffer *b, OFP_Packet_Out& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, OFP_Packet_Out& obj) {obj.parsimUnpack(b);}


#endif // ifndef _OFP_PACKET_OUT_M_H_

